# Définition du rôle (Role) dans le namespace gitlab-runner
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: gitlab-runner
  name: gitlab-runner-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log", "services", "configmaps", "secrets","persistentvolumeclaims"]
    verbs: ["get", "list", "create", "delete", "patch", "update"]
